plugins {
    id 'antlr'
}

intellij {
    plugins = []
}

configurations {
    antlr4
}

dependencies {
    implementation 'com.google.code.gson:gson:2.9.0'
    antlr4 'org.antlr:antlr4:4.13.1'
    implementation 'org.antlr:antlr4-runtime:4.13.1'
    compileOnly 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.3'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.9.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.3'
}

task generateDslExpressionGrammar(type: JavaExec) {
    description 'Generate ANTLR4 parser for DslExpression grammar'
    group 'antlr'
    classpath = configurations.antlr4
    mainClass = 'org.antlr.v4.Tool'
    args = [
            '-package', 'com.huawei.theme.analysis.core.expression.generated',
            '-visitor', '-no-listener',
            '-o', file('src/main/java/com/huawei/theme/analysis/core/expression/generated').absolutePath,
            file('src/main/java/com/huawei/theme/analysis/core/expression/grammar/DslExpression.g4').absolutePath
    ]
}

task generateDslRuleConditionGrammar(type: JavaExec) {
    description 'Generate ANTLR4 parser for DslRuleCondition grammar'
    group 'antlr'
    classpath = configurations.antlr4
    mainClass = 'org.antlr.v4.Tool'
    args = [
            '-package', 'com.huawei.theme.analysis.core.ruledsl.generated',
            '-visitor', '-no-listener',
            '-o', file('src/main/java/com/huawei/theme/analysis/core/ruledsl/generated').absolutePath,
            file('src/main/java/com/huawei/theme/analysis/core/ruledsl/grammar/DslRuleCondition.g4').absolutePath
    ]
}

compileJava.dependsOn generateDslExpressionGrammar, generateDslRuleConditionGrammar

test {
    useJUnitPlatform()
}